[package]
name = "pushover-wait-issue"
version = "0.1.0"

[dependencies]
regex = "0.2"
iron = "0.6"
askama = { version = "0.5", features = ["with-iron"] }
pushover = "0.2.0"
ws = "*"
serde_json = "1.0"
mount = "*"
staticfile = "*"

